apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: lrochette/my-simple-node:1.0.2
      imagePullPolicy: Always
      ports:
        - containerPort: 3000 