apiVersion: batch/v1
kind: CronJob
metadata:
  name: temp-cleaner
spec:
  schedule: "*/1 * * * *"  # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: temp-cleaner
            image: busybox
            command: ["/bin/sh", "-c"]
            args: ['echo "Cleaning temp files at $(date)"']
          restartPolicy: OnFailure