apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeweb
  template:
    metadata:
      labels:
        app: nodeweb
    spec:
      containers:
      - name: nodeweb
        image: lrochette/my-simple-node:1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 3000