apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-demo-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/persistent-storage  # /tmp/k8s-storage-demo-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-demo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
