apiVersion: v1
kind: Pod
metadata:
  name: storage-demo-pod
spec:
  volumes:
  - name: ephemeral-logs
    emptyDir: {}
  - name: persistent-data
    persistentVolumeClaim:
      claimName: storage-demo-pvc
  containers:
  - name: nginx
    image: nginx-storage-demo:1.0
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    volumeMounts:
    - name: ephemeral-logs
      mountPath: /var/log/nginx
    - name: persistent-data
      mountPath: /usr/share/nginx/uploads